version: '3.8'

services:
  machbase:
    image: machbase/machbase-neo
    restart: always
    ports:
      - "5435:5654"
    volumes:
      - /database/machbase/data:/data
      - /database/machbase/file:/file
      - /database/machbase/metrics:/metrics
      - /etc/localtime:/etc/localtime:ro
    blkio_config:
      device_read_iops:
        - path: /dev/sda
          rate: 100
      device_write_iops:
        - path: /dev/sda
          rate: 100
    cpuset: "0,2"
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 2GB
        reservations:
          memory: 1GB