version: '3.8'

services:
  machbase:
    image: machbase/machbase-neo
    restart: always
    ports:
      - "5654:5654"
      - "5656:5656"
    volumes:
      - /database/machbase/data:/data
      - /database/machbase/file:/file
      - /database/machbase/metrics:/metrics
      - /etc/localtime:/etc/localtime:ro
    blkio_config:
      device_read_iops:
        - path: /dev/sda
          rate: 1000
      device_write_iops:
        - path: /dev/sda
          rate: 1000
    cpuset: "0,1,2,3"
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 4GB
        reservations:
          memory: 1GB