version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server
    restart: always
    ports:
      - "5436:9000"
      - "8443:8443"
      - "9123:8123"
    environment:
      - CLICKHOUSE_USER=alex
      - CLICKHOUSE_PASSWORD=alex123
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_DB=stock_db
    volumes:
      - /database/clickhouse/data:/var/lib/clickhouse/
      - /database/clickhouse/logs:/var/log/clickhouse-server/
      - /database/clickhouse/config.xml:/etc/clickhouse-server/config.xml
      - /database/clickhouse/metrics:/var/lib/clickhouse/metrics
      - /etc/localtime:/etc/localtime:ro
    blkio_config:
      device_read_iops:
        - path: /dev/sda
          rate: 100
      device_write_iops:
        - path: /dev/sda
          rate: 100
    cpuset: "0,2"
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 2GB
        reservations:
          memory: 1GB