version: '3.8'

services:
  clickhouse:
    image: yandex/clickhouse-server
    restart: always
    ports:
      - "8888:9000"
      - "8443:8443"
      - "8123:8123"
    environment:
      - CLICKHOUSE_USER=alex
      - CLICKHOUSE_PASSWORD=alex123
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_DB=stock_db
    volumes:
      - /database/clickhouse/data:/var/lib/clickhouse/
      - /database/clickhouse/metrics:/var/lib/clickhouse/metrics
      - /etc/localtime:/etc/localtime:ro
    blkio_config:
      device_read_iops:
        - path: /dev/sda
          rate: 1000
      device_write_iops:
        - path: /dev/sda
          rate: 1000
    cpuset: "0,1,2,3"
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 4GB
        reservations:
          memory: 1GB